#!/bin/sh

# Modified from https://github.com/zalando/docker-openjdk
#
# example usage: 
# exec java $(dynamic-memory-opts) -jar myfatjar.jar
# exec sbt -J$(dynamic-memory-opts) MyApplication

DEFAULT_MEM_JAVA_PERCENT=80

if [ -z "$MEM_JAVA_PERCENT" ]; then
    if [ -n "$1" ]; then
        MEM_JAVA_PERCENT=$1
    else
        MEM_JAVA_PERCENT=$DEFAULT_MEM_JAVA_PERCENT
    fi
fi

# If MEM_TOTAL_MB is set, the heap is set to a percent of that
# value equal to MEM_JAVA_PERCENT; otherwise it uses the default
# memory settings.
if [ ! -z "$MEM_TOTAL_MB" ]; then
    MEM_JAVA_MB=$(($MEM_TOTAL_MB * $MEM_JAVA_PERCENT / 100))
    echo "-Xmx${MEM_JAVA_MB}m"
fi
